name: ideasoft_case_project_shop
description: "IdeaSoft case project made by Mirac Altinay."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.1.1
  auto_route: ^7.8.4
  logger: ^2.0.2+1 #for logging purpose
  cached_network_image: ^3.2.3
  flutter_easyloading: ^3.0.5
  overlay_support: ^2.1.0
  cupertino_icons: ^1.0.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  freezed: ^2.3.0 #code generator for unions/pattern-matching/copy
  json_serializable: ^6.5.4 #code generator for fromJson/toJson
  shared_preferences: ^2.2.2
  carousel_slider: ^5.0.0
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  flutter_lints: ^3.0.1
  get_it: ^7.6.4
  custom_rating_bar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.12


  flavor: ^2.0.0
  retrofit_generator: ^8.0.5


dependency_overrides:
  win32: ^5.3.0
  retrofit:
    git:
      url: https://github.com/trevorwang/retrofit.dart
      path: retrofit

flutter:

  uses-material-design: true









  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

